services:
  Acme\IpBlockerBundle\:
    resource: '../../src/*'
    exclude: '../../src/{DependencyInjection,Entity,Tests,Kernel.php}'
    autowire: true
    autoconfigure: true
    public: false

  Acme\IpBlockerBundle\EventSubscriber\IpBlockerSubscriber:
    public: true
    tags: ['kernel.event_subscriber']
